---
title: "flat_paths_and_files.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# current_script_location
    
```{r development-current_script_location}
# You can prepare the code of the current_script_location() function here
```
  
```{r function-current_script_location}
#' RStudio only - Get exact path of the currently opened script
#' 
#' This function only works in RStudio and with an opened source document.  
#' There is exceptionnaly no example and exact test since these are running in background sessions in checks. 
#' 
#' @return Character 1L. A character vector indicating exact path of currently opened script
#' @export
#'
current_script_location <- function () {

  if (.Platform$GUI != "RStudio") {
    
    stop("This function is not working without RStudio")
  }
  
  dirname(
    path = rstudioapi::getSourceEditorContext()$path)
}
```
    
```{r tests-current_script_location}
test_that("No exact test but RStudio should not be available in the tests", {
  
  expect_false(.Platform$GUI == "RStudio")
  
  expect_error(current_script_location())
})
```
  
```{r dev, eval = FALSE}
# Trial to do a more precise test of current_script_location() : 
 temp_filepath <- tempfile(pattern = "csloc")
  code <- "
  out_path <- current_script_location()
  writeLines(out_path, file.path(out_path, 'out_code'))
  "
  writeLines(text = code, con = temp_filepath)
  job::job({source(temp_filepath)})
  out_code_text <- readLines(file.path(basename(temp_filepath), "out_code"))
    
  expect_identical(
    object = current_script_location(), 
    expected = out_code_text)
```

# folder_structure_replicate
    
```{r development-folder_structure_replicate}
# You can prepare the code of the folder_structure_replicate() function here
```
  
```{r function-folder_structure_replicate}
#' Replicate the folder structure of a given directory
#'
#' @param dir Character 1L. Path of directory which structure will be replicated
#' @param to Character 1L. Path of an output directory in which replicated structured will be placed
#' @return No return value, called for side effects. The directory
#'   structure of \code{dir} is recreated inside the \code{to} directory.
#' @importFrom magrittr %>%
#' @export
#'
folder_structure_replicate <- function (dir, to) {

  requireNamespace("magrittr")

  if (isTRUE(identical(dir, to))) {
    
    stop(glue::glue("The arguments dir and to must not be identical"))
  }
  
  if (isTRUE(
    length(list.dirs(to, recursive = FALSE)) > 0)) {
    
    stop(glue::glue("For security reasons, {to} must be an empty directory"))
  }
  
  # Warnings are suppressed because of the two security checks above: 
  suppressWarnings({
    
    list.dirs(dir, full.names = FALSE) %>%
      (\(l) for (i in l)
        dir.create(file.path(to, i), recursive = TRUE))
  })
  
}
```
  
```{r example-folder_structure_replicate}
library(magrittr)

temp_dir_to_replicate <- tempfile()
dir.create(temp_dir_to_replicate)

dir.create(file.path(temp_dir_to_replicate, "dir1"))
dir.create(file.path(temp_dir_to_replicate, "dir2"))

temp_dir_out <- tempfile()
dir.create(temp_dir_out)

folder_structure_replicate(
  dir = temp_dir_to_replicate, 
  to = temp_dir_out)

unlink(temp_dir_to_replicate)
unlink(temp_dir_out)
```
  
```{r tests-folder_structure_replicate}
test_that("Structures are effectively the same", {
  
  library(magrittr)
  
  temp_dir_to_replicate <- tempfile()
  dir.create(temp_dir_to_replicate)
  
  dir.create(file.path(temp_dir_to_replicate, "dir1"))
  dir.create(file.path(temp_dir_to_replicate, "dir2"))
  
  temp_dir_out <- tempfile()
  dir.create(temp_dir_out)
  
  folder_structure_replicate(
  dir = temp_dir_to_replicate, 
  to = temp_dir_out)
  
  ldir_in <- temp_dir_to_replicate %>% 
    (\(t) list.dirs(t) %>% 
       (\(l) l[l != t]))
  ldir_out <- temp_dir_to_replicate %>% 
    (\(t) list.dirs(t) %>% 
       (\(l) l[l != t]))
  
  expect_identical(
    object = ldir_in, 
    expected = ldir_out
  )
})
```
  
# path_move
    
```{r development-path_move}
# You can prepare the code of the path_move() function here

epath <- c("n1/n2/n3/f1", "n1/n2/n3/f2")
split <- strsplit(epath, "/")

plevels <- map_dbl(split, length)

if (isFALSE(length(rle(plevels)$values) == 1)) {
  
  df_error <- data.frame("path_vector" = epath, 
             "number_of_levels" = plevels)
  
  print(df_error)
  
  stop("All path_vector elements must have the same number of levels")
}

pmatrix <- split %>% do.call(what = rbind)
ncol <- ncol(pmatrix)
upmove <- - 1
upmove <- as.integer(upmove)

if (isTRUE(abs(upmove) >= ncol(pmatrix))) {
  
  stop(glue::glue("upmove absolute value must be strictly positive and strictly lesser than {ncol}"))
}
pmatrix[, - (ncol(pmatrix):(ncol(pmatrix) + upmove + 1)), drop = FALSE] %>% 
  apply(1, \(x) paste(x, collapse = "/"))# ok. 

level <- 2

if (isFALSE(level %in% 1:ncol)) {
  
  stop(glue::glue("level must be comprised between one of these values : {1:ncol}"))
}

pmatrix[, 1:level, drop = FALSE] %>% 
  apply(1, \(x) paste(x, collapse = "/"))


path_move <- function (path_vector, path_separator = "/", move) {
  
  if (isFALSE(is.character(path_vector))) {
    
    stop("path_vector must be a character vector")
  }
  
  if (isFALSE(is.numeric(move))) {
    
    stop("move must be a numeric")
  }
  
  if (isTRUE(move == 0)) {
    
    stop("move must be different from 0")
  }
  
  split <- strsplit(path_vector, path_separator)
  plevels <- purrr::map_dbl(split, length)
  
  if (isFALSE(length(rle(plevels)$values) == 1)) {
    
    df_error <- data.frame("path_vector" = epath, 
                           "number_of_levels" = plevels)
    
    print(df_error)
    
    stop("All path_vector elements must have the same number of levels")
  }
  
  pmatrix <- split %>% do.call(what = rbind)
  ncol <- ncol(pmatrix)
  move <- as.integer(move)
  
  if (move > 0) {
    
    if (isFALSE(level %in% 1:ncol)) {
      
      stop(glue::glue("level must be comprised between one of these values : {1:ncol}"))
    }
    
    pmatrix[, 1:level, drop = FALSE] %>% 
      apply(1, \(x) paste(x, collapse = path_separator))
    
  } else {
    
    if (isTRUE(abs(upmove) >= ncol(pmatrix))) {
  
      stop(glue::glue(
        "upmove absolute value must be strictly positive and strictly lesser than {ncol}"))
    }
    
    pmatrix[, - (ncol(pmatrix):(ncol(pmatrix) + upmove + 1)), drop = FALSE] %>% 
      apply(1, \(x) paste(x, collapse = path_separator))
  }
}
```

```{r function-path_move}
#' Move through paths
#'
#' @param path_vector Character. Vector of paths with equal number of levels
#' @param path_separator Character 1L. Path separator 
#' (adapted to your OS for instance)
#' @param move Integer 1L. 
#' If move > 0, outputs path till specified level in move. 
#' If move < 0, remove the last specified level(s) in move.
#'
#' @return Character. Transformed vector of paths. 
#' @importFrom magrittr %>% 
#' @importFrom glue glue
#' @export
#'
#' @examples
path_move <- function (path_vector, path_separator = "/", move) {
  
  if (isFALSE(is.character(path_vector))) {
    
    stop("path_vector must be a character vector")
  }
  
  if (isFALSE(is.numeric(move))) {
    
    stop("move must be a numeric")
  }
  
  if (isTRUE(move == 0)) {
    
    stop("move must be different from 0")
  }
  
  split <- strsplit(path_vector, path_separator)
  plevels <- purrr::map_dbl(split, length)
  
  if (isFALSE(length(rle(plevels)$values) == 1)) {
    
    df_error <- data.frame("path_vector" = path_vector, 
                           "number_of_levels" = plevels)
    
    print(df_error)
    
    stop("All path_vector elements must have the same number of levels")
  }
  
  pmatrix <- split %>% do.call(what = rbind)
  ncol <- ncol(pmatrix)
  move <- as.integer(move)
  
  if (move > 0) {
    
    if (isFALSE(move %in% 1:ncol)) {
      
      stop(glue::glue("level must be comprised between one of these values : {
                      paste(1:ncol, collapse = ', ')}"))
    }
    
    pmatrix[, 1:move, drop = FALSE] %>% 
      apply(1, \(x) 
            paste(x, collapse = path_separator))
    
  } else {
    
    if (isTRUE(abs(move) >= ncol(pmatrix))) {
      
      stop(glue::glue(
        "move absolute value must be strictly positive and strictly lesser than {ncol}"))
    }
    
    pmatrix[, - (ncol(pmatrix):(ncol(pmatrix) + move + 1)), drop = FALSE] %>% 
      apply(1, \(x) 
            paste(x, collapse = path_separator))
  }
}
```
  
```{r example-path_move}
pvector <- c(
  "level_1/level_2/level_3/file_1.ext", 
  "level_1/level_2/level_3/file_2.ext"
)

path_move(path_vector = pvector, 
          path_separator = "/", 
          move = 1)

path_move(path_vector = pvector, 
          path_separator = "/", 
          move = 2)

path_move(path_vector = pvector, 
          path_separator = "/", 
          move = - 1)

path_move(path_vector = pvector, 
          path_separator = "/", 
          move = - 2)
```
  
```{r tests-path_move}
test_that("Valid outputs are consistent", {
 
  pvector <- c(
    "level_1/level_2/level_3/file_1.ext", 
    "level_1/level_2/level_3/file_2.ext"
  )
  
  expect_identical(
    object = path_move(pvector, "/", 1),
    expected = c("level_1", "level_1")
  )
  
  expect_identical(
    object = path_move(pvector, "/", 2),
    expected = c("level_1/level_2", "level_1/level_2")
  )
  
  expect_identical(
    object = path_move(pvector, "/", 3),
    expected = c("level_1/level_2/level_3", 
                 "level_1/level_2/level_3")
  )
  
  expect_identical(
    object = path_move(pvector, "/", - 1), 
    expected = c("level_1/level_2/level_3", 
                 "level_1/level_2/level_3")
    )
  
  expect_identical(
    object = path_move(pvector, "/", - 2), 
    expected = c("level_1/level_2", 
                 "level_1/level_2")
    )
  
  expect_identical(
    object = path_move(pvector, "/", - 3), 
    expected = c("level_1", 
                 "level_1")
    )
  
})

test_that("Errors are consistent", {
 
  pvector <- c(
    "level_1/level_2/level_3/file_1.ext", 
    "level_1/level_2/level_3/file_2.ext"
  )
  
  expect_error(
    object = path_move(pvector, "/", 0), 
    regexp = "move must be different from 0"
  )
  
  expect_error(
    object = path_move(pvector, "/", 5),
    regexp = "level must be comprised between one of these values : 1, 2, 3, 4"
  )
  
  expect_error(
    object = path_move(pvector, "/", -4),
    regexp = "move absolute value must be strictly positive and strictly lesser than 4"
  )
})
```
    
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_paths_and_files.Rmd", 
               vignette_name = NA)
```

